<a href="https://colab.research.google.com/github/tareqalmamun/hello-world/blob/master/ML_Project_Code_Sentiment_Analysis_V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import model_selection
from pandas.plotting import parallel_coordinates
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.metrics import roc_auc_score
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import precision_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [3]:
data = pd.read_csv('/content/drive/MyDrive/Colab_Data/ML_Project_Model_Input_V1.csv')
data.head(5)
data

Filename  WC  WPS  Qmarks  Unique  ...  death  assent  nonfl  filler  Label
0        2.txt   4    4       0   100.0  ...    0.0     0.0   25.0     0.0      1
1        3.txt   6    6       0   100.0  ...    0.0     0.0    0.0     0.0      1
2        4.txt   6    6       0   100.0  ...    0.0     0.0    0.0     0.0      1
3        5.txt   3    3       0   100.0  ...    0.0     0.0    0.0     0.0      1
4        6.txt   5    5       0   100.0  ...    0.0     0.0    0.0     0.0      3
...        ...  ..  ...     ...     ...  ...    ...     ...    ...     ...    ...
1788  1790.txt   6    6       0   100.0  ...    0.0     0.0    0.0     0.0      3
1789  1791.txt   5    5       0   100.0  ...    0.0     0.0    0.0     0.0      1
1790  1792.txt   6    6       0   100.0  ...    0.0     0.0    0.0     0.0      1
1791  1793.txt   5    5       0   100.0  ...    0.0     0.0    0.0     0.0      1
1792  1794.txt   6    6       0   100.0  ...    0.0     0.0    0.0     0.0      1

[1793 rows x 72 columns]

In [4]:
data.groupby('Label').size()

Label
1    696
2    492
3    605
dtype: int64

In [21]:
# Selecting only Features to use for Modeling
data = data[['we','ipron', 'pronoun', 'health', 'bio', 'affect', 'posemo', 'present', 'verb', 'anger', 'Label']] #// 'percept','hear','relativ','time','we','auxverb','future','swear','anger','number'
#feature_data = data[['pronoun','ipron', 'affect', 'posemo', 'bio','we','Label']]
#feature_data = data[['Unique', 'Dic', 'Sixltr', 'funct', 'pronoun', 'ppron','we','ipron','verb','negemo','social','health','bio', 'affect','posemo', 'family', 'present', 'work', 'verb', 'anger', 'Label']]
data


we  ipron  pronoun  health    bio  ...  posemo  present   verb  anger  Label
0     0.0   0.00     0.00   25.00  25.00  ...   25.00     0.00   0.00    0.0      1
1     0.0   0.00     0.00    0.00   0.00  ...    0.00    16.67  16.67    0.0      1
2     0.0   0.00     0.00    0.00   0.00  ...   16.67     0.00  16.67    0.0      1
3     0.0  33.33    33.33    0.00   0.00  ...    0.00    33.33  33.33    0.0      1
4     0.0   0.00     0.00    0.00   0.00  ...   20.00     0.00  20.00    0.0      3
...   ...    ...      ...     ...    ...  ...     ...      ...    ...    ...    ...
1788  0.0   0.00     0.00   33.33  33.33  ...    0.00    16.67  16.67    0.0      3
1789  0.0   0.00     0.00    0.00   0.00  ...    0.00    20.00  20.00    0.0      1
1790  0.0   0.00     0.00    0.00   0.00  ...    0.00    33.33  33.33    0.0      1
1791  0.0   0.00     0.00    0.00   0.00  ...   20.00    20.00  40.00    0.0      1
1792  0.0   0.00     0.00    0.00   0.00  ...    0.00    16.67  16.67    0.0      1

[1793 rows x 11 columns]

In [22]:
#split-out validation dataset
array = data.values
X = array[:,0:9] #// Selecting Column //
Y = array[:,10] 

In [23]:
#train/test set
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.2, random_state=12345)

In [33]:
#KNN Classifiers
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, Y_train)
predictions = knn.predict(X_test)
print("Accuracy Score:", accuracy_score(Y_test, predictions))
#print(confusion_matrix(Y_test, predictions))
#print(classification_report(Y_test, predictions))
predictions_proba = knn.predict_proba(X_test)
print("ROC_AUC_Score:", roc_auc_score(Y_test,predictions_proba,multi_class="ovr"))
print("MCC:", matthews_corrcoef(Y_test, predictions))
print("Precision Score:",precision_score(Y_test, predictions, average='weighted'))
print("f1 Score:", f1_score(Y_test, predictions, average="micro"))

Accuracy Score: 0.40947075208913647
ROC_AUC_Score: 0.5821754923727129
MCC: 0.09894106095131813
Precision Score: 0.41376566395159525
f1 Score: 0.4094707520891364


In [34]:
#Gaussian Classifiers
from sklearn.gaussian_process.kernels import RBF
kernel = 2.0 * RBF(2.0)
model = GaussianProcessClassifier(kernel=kernel, random_state=0)
y_score  = model.fit(X_train, Y_train)
predictions = model.predict(X_test)
predictions=model.predict(X_test)
score = metrics.accuracy_score(Y_test , predictions)
print("Accuracy Score:", accuracy_score(Y_test, predictions))
#print(confusion_matrix(Y_test, predictions))
#print(classification_report(Y_test, predictions))
predictions_proba = knn.predict_proba(X_test)
print("ROC_AUC_Score:", roc_auc_score(Y_test,predictions_proba,multi_class="ovr"))
print("MCC:", matthews_corrcoef(Y_test, predictions))
print("Precision Score:",precision_score(Y_test, predictions, average='weighted'))
print("f1 Score:", f1_score(Y_test, predictions, average="micro"))


Accuracy Score: 0.3788300835654596
ROC_AUC_Score: 0.5821754923727129
MCC: 0.027031871352146946
Precision Score: 0.36622995504112965
f1 Score: 0.3788300835654596


In [27]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
#y_score = model.fit(X_train, Y_train)  
model.fit(X_train, Y_train)
predictions=model.predict(X_test)
score = metrics.accuracy_score(Y_test , predictions)
print("Accuracy Score:", accuracy_score(Y_test, predictions))
#print(confusion_matrix(Y_test, predictions))
#print(classification_report(Y_test, predictions))
predictions_proba = knn.predict_proba(X_test)
print("ROC_AUC_Score:", roc_auc_score(Y_test,predictions_proba,multi_class="ovr"))
print("MCC:", matthews_corrcoef(Y_test, predictions))
print("Precision Score:",precision_score(Y_test, predictions, average='weighted'))
print("f1 Score:", f1_score(Y_test, predictions, average="micro"))


Accuracy Score: 0.3203342618384401
ROC_AUC_Score: 0.5022734609465677
MCC: 0.012651226651386387
Precision Score: 0.3757789125680216
f1 Score: 0.3203342618384401


In [36]:
# Decision tree classifier 
model = DecisionTreeClassifier(max_depth=8,random_state=42)
model.fit(X_train, Y_train)
predictions=model.predict(X_test)
score = metrics.accuracy_score(Y_test , predictions)
print("Accuracy Score:", accuracy_score(Y_test, predictions))
#print(confusion_matrix(Y_test, predictions))
#print(classification_report(Y_test, predictions))
predictions_proba = knn.predict_proba(X_test)
print("ROC_AUC_Score:", roc_auc_score(Y_test,predictions_proba,multi_class="ovr"))
print("MCC:", matthews_corrcoef(Y_test, predictions))
print("Precision Score:",precision_score(Y_test, predictions, average='weighted'))
print("f1 Score:", f1_score(Y_test, predictions, average="micro"))


Accuracy Score: 0.4011142061281337
ROC_AUC_Score: 0.5821754923727129
MCC: 0.07640627414569373
Precision Score: 0.39917885679347526
f1 Score: 0.4011142061281337


In [ ]:
# Support Vector Machine 
from sklearn import svm
model = svm.SVC(kernel='linear') # Linear Kernel
model.fit(X_train, Y_train)
predictions=model.predict(X_test)
score = metrics.accuracy_score(Y_test , predictions)
print("Accuracy Score : ",score)
print(confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))
#predictions_proba = model.predict_proba(X_test)
#roc_auc = roc_auc_score(Y_test,predictions_proba,multi_class="ovr")
print("ROC AUC Score : ",roc_auc)
mcc = matthews_corrcoef(Y_test, predictions)
print("MCC : ",mcc)
ps = precision_score(Y_test, predictions, average='weighted')
print("precision_score : ",ps)



Accuracy Score :  0.38997214484679665
[[82  8 57]
 [47  9 45]
 [55  7 49]]
              precision    recall  f1-score   support

         1.0       0.45      0.56      0.50       147
         2.0       0.38      0.09      0.14       101
         3.0       0.32      0.44      0.37       111

    accuracy                           0.39       359
   macro avg       0.38      0.36      0.34       359
weighted avg       0.39      0.39      0.36       359

ROC AUC Score :  0.5523721923184394
MCC :  0.05167848104576036
precision_score :  0.38831681647600635


In [ ]:
model = RandomForestClassifier()
model.fit(X_train, Y_train)
predictions=model.predict(X_test)
score = metrics.accuracy_score(Y_test , predictions)
print("Accuracy Score:", accuracy_score(Y_test, predictions))
#print(confusion_matrix(Y_test, predictions))
#print(classification_report(Y_test, predictions))
predictions_proba = knn.predict_proba(X_test)
print("ROC_AUC_Score:", roc_auc_score(Y_test,predictions_proba,multi_class="ovr"))
print("MCC:", matthews_corrcoef(Y_test, predictions))
print("Precision Score:",precision_score(Y_test, predictions, average='weighted'))
print("f1 Score:", f1_score(Y_test, predictions, average="micro"))


Accuracy Score: 0.3788300835654596
ROC_AUC_Score: 0.5317004965685818
MCC: 0.04337997971403421
Precision Score: 0.3730464252553389
f1 Score: 0.3788300835654596
